use crate::tool::Tool;
use crate::tool::ToolContext;
use crate::tool::ToolOutput;
use serde_json::Value;
use std::future::Future;
use std::pin::Pin;

pub type ToolFuture<'a> = Pin<Box<dyn Future<Output = Result<ToolOutput, String>> + Send + 'a>>;

/// A tool generated by `#[tool]`. One concrete type, so `.tools([a, b])` is a homogeneous array.
#[derive(Debug, Clone, Copy)]
pub struct ToolDef {
    name: &'static str,
    description: &'static str,
    input_schema: fn() -> Value,
    call: for<'a> fn(Value, &'a ToolContext) -> ToolFuture<'a>,
}

impl ToolDef {
    pub const fn new(
        name: &'static str,
        description: &'static str,
        input_schema: fn() -> Value,
        call: for<'a> fn(Value, &'a ToolContext) -> ToolFuture<'a>,
    ) -> Self {
        Self {
            name,
            description,
            input_schema,
            call,
        }
    }
}

impl Tool for ToolDef {
    type Output = ToolOutput;
    type Error = String;

    fn name(&self) -> &str {
        self.name
    }

    fn description(&self) -> &str {
        self.description
    }

    fn input_schema(&self) -> Value {
        (self.input_schema)()
    }

    fn call(
        &self,
        input: Value,
        context: &ToolContext,
    ) -> impl Future<Output = Result<ToolOutput, String>> + Send {
        (self.call)(input, context)
    }
}
