//! Support for code generated by `#[tool]`; not public API and exempt from semver.
//! The re-exports let generated code resolve `serde`, `serde_json` and `schemars` through this
//! crate, so users do not need them as direct dependencies.

pub use schemars;
use schemars::JsonSchema;
use schemars::generate::SchemaSettings;
pub use serde;
pub use serde_json;
use serde_json::Value;

const SCHEMA_TITLE_KEY: &str = "title";

pub fn input_schema<T: JsonSchema>() -> Value {
    let mut settings = SchemaSettings::draft2020_12();
    settings.meta_schema = None;
    settings.inline_subschemas = true;
    let mut schema = settings.into_generator().into_root_schema_for::<T>();
    schema.remove(SCHEMA_TITLE_KEY);
    schema.to_value()
}
